notifications:
  email: false

branches:
  only:
    - master
    - dev
    - testing
    - refactor

dist: trusty
group: edge
sudo: required

matrix:
  include:
    - language: python
      python: "3.4"
      services:
        - docker
    - language: python
      python: "3.5"
      services:
        - docker
    - language: python
      python: "3.6"
      services:
        - docker
    - language: python
      python: "nightly"
      services:
        - docker
    - language: generic
      os: osx
      before_install:
        - brew update
        - brew install python3
        - virtualenv env -p python3
        - source env/bin/activate
        - brew install openldap --with-sssvlv
        - pip3 install tornado
        - pip3 install codecov
        - pip3 install pytest-cov
        - pip3 install delocate
        - printf "[build_ext]\ninclude_dirs=/usr/local/opt/openldap/include\nlibrary_dirs=/usr/local/opt/openldap/lib" > ./setup.cfg
        - cp ./tests/testenv/slapd.conf /usr/local/etc/
        - mkdir /usr/local/var/openldap-data
        - ./tests/testenv/configure_ldap.sh
        - ls /usr/local/var/openldap-data
        - ls /usr/local/var/openldap-certs
        - sudo python3 ./tests/testenv/delay.py &
        - sudo /usr/local/opt/openldap/libexec/slapd -h "ldap:// ldaps://"
      before_script:
        - export KRB5_CONFIG="$TRAVIS_BUILD_DIR/tests/testenv/krb5/krb5.conf"
        - INSTALL_PATH=`python3 -c "import bonsai; print(bonsai.__file__[:-12])"`
        - echo $INSTALL_PATH

before_install:
  - sudo apt-get update
  - sudo apt-get install -y libldap2-dev libsasl2-dev ldap-utils
  # For GSSAPI authentication.
  - sudo apt-get install -y krb5-user libsasl2-modules-gssapi-mit libkrb5-dev
  - if [[ $TRAVIS_PYTHON_VERSION != 'nightly' ]]; then pip install gevent; fi
  - pip install tornado
  - pip install codecov
  - pip install pytest-cov
  - docker build -t bonsai ./tests/testenv
  - docker run --cap-add=NET_ADMIN -d -h bonsai.test --name server bonsai
  # Set container IP in the hosts file.
  - DOCKER_IP=`docker inspect --format '{{ .NetworkSettings.IPAddress }}' server`
  - sudo bash -c 'echo -e "\n'$DOCKER_IP'        bonsai.test" >> /etc/hosts'
  - cat /etc/hosts
  - ping -c 2 bonsai.test
  # Waiting for slapd to start in the container.
  - sleep 4
  # Check that everything is started.
  - docker exec server ps aux
  - docker exec server /bin/bash -c "cat /var/log/supervisord.log"
  # Check that slapd is working.
  - ldapwhoami -Y DIGEST-MD5 -h bonsai.test -U admin -w p@ssword
  - ldapsearch -h bonsai.test -b "" -s base 'objectclass=*' -x -LLL +
  - ldapsearch -VV

install:
  - export CFLAGS="-coverage"
  - python setup.py install

before_script:
  # Change localhost IP in test.ini to the container's.
  - sed -i.bak "s/127.0.0.1/$DOCKER_IP/g" ./tests/test.ini
  # Set used Kerberos config file to my own.
  - export KRB5_CONFIG="$TRAVIS_BUILD_DIR/tests/testenv/krb5/krb5.conf"
  # Set install path for coverage.py.
  - INSTALL_PATH=`python -c "import bonsai; print(bonsai.__file__[:-12])"`
  - echo $INSTALL_PATH

script:
  - py.test -v --cov-config .coveragerc --cov-report= --cov=$INSTALL_PATH

after_success:
  # Change path of the Python source files in .coverage.
  - sed -i.bak 's|'$INSTALL_PATH'|'$TRAVIS_BUILD_DIR/lib'|g' .coverage
  - codecov

#after_failure:
  # Print out slapd log for debugging.
  #- docker exec server cat /var/log/slapd.log
